[package]
name = "macro_railroad_wasm"
version = "0.1.0"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
build = "build.rs"

[dependencies]
railroad = "0.1"
macro_railroad = "0.1"
stdweb = { version = "0.4", default_features=false }
htmlescape = "0.3"
syn = { version = "0.15", default_features=false }

[lib]
crate-type = ["cdylib"]

[build-dependencies]
built = { version = "0.3", features=["serialized_time"], default_features=false }
